{
    "Dialing code": "+256",
    "ISO 2 code": "UG",
    "ISO 3 code": "UGA",
    "Capital": "Kampala",
    "Main Language": "English",
    "Currency": "Shilling (UGX)",
    "GDP": "$35.9 billion",
    "Population": "33,398,682",
    "Continent": "Africa",
    "Location": "Eastern Africa west of Kenya",
    "Land": "236,040 km2",
    "Terrain": "Mostly plateau with rim of mountains",
    "Climate": "Tropical; generally rainy with two dry seasons (December to February June to August); semiarid in northeast",
    "Natural Hazards": "Mostly plateau with rim of mountains",
    "Note:": "Landlocked; fertile well-watered country with many lakes and rivers",
    "Life Expectancy": "52.72 years",
    "Median Age": "15.0 years",
    "Birth Rate": "47.84 births/1,000 population",
    "Death Rate": "12.09 births/1,000 population",
    "Sex Ratio": "0.71 male(s)/female",
    "Literacy": "66.8%",
    "Roadways": "70746 km",
    "Railways": "1244 km",
    "Airports": "33",
    "Waterways": "None km",
    "Heliports": "None",
    "Airports paved": "1",
    "GDP per capita (PPP)": "$1100"
}